export const EXAMPLE_PATH = 'blog-starter'
export const CMS_NAME = 'TEOleigo'
export const CMS_SUBTITLE = 'Discussões teológicas de um leigo na internet'
export const CMS_URL = 'https://teoleigo.com.br'
export const HOME_OG_IMAGE_URL = '%20Starter%20Example.png?theme=light&md=1&fontSize=100px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg'
